### ISSUE TITLE
When falling out of the tutorial level, the gun equipped disappears

### ISSUE THREAD

**Issue by NavigateByCloud** [denniscarr/dada#87]

**Comment by denniscarr** [comment]
I managed to figure out what's causing this bug, it was really weird.

The gun doesn't disappear, it just has it's position changed. It is still in the scene and equipped to the player, but it's far away.

This doesn't have to do with scripting. It happens with any object when:
A) It's collision detection is set to Interpolate
and B) The player is moving the mouse when they enter the killzone's trigger.

I had the collision set to Interpolate on the AK12 because previously it kept falling through the ground. I set the Interpolate setting in the prefab back to 'None' and it fixed the bug, but the gun may begin to fall through the floor again.
